# Generated by Django 4.0.1 on 2022-04-21 12:07

from django.db import migrations, models
import django.db.models.deletion
import scores.utils
import scores.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=scores.utils.upload_to)),
                ('skin_color', models.CharField(choices=[('Black', 'Black'), ('White', 'White')], default='Black', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric', models.PositiveIntegerField(default=1, validators=[scores.validators.numeric_score_validator])),
                ('emotion', models.CharField(choices=[('Loving', 'Loving'), ('Compationate', 'Compationate'), ('Sympathic', 'Sympathic'), ('Intelligent', 'Intelligent'), ('Disciplined', 'Disciplined'), ('Stunning', 'Stunning'), ('Lovely', 'Lovely'), ('Adventurous', 'Adventurous'), ('Agreeable', 'Agreeable'), ('Ambitious', 'Ambitious'), ('Bright', 'Bright'), ('Charming', 'Charming'), ('Courageous', 'Courageous'), ('Courteous', 'Courteous'), ('Inventive', 'Inventive'), ('Likable', 'Likable'), ('Passionate', 'Passionate'), ('Sensible', 'Sensible'), ('Trustworthy', 'Trustworthy'), ('Witty', 'Witty'), ('Sleek', 'Sleek'), ('Smooth', 'Smooth'), ('Healthy', 'Healthy'), ('Radiant', 'Radiant'), ('Vibrant', 'Vibrant'), ('Polished', 'Polished'), ('Immaculate', 'Immaculate'), ('Seductive', 'Seductive'), ('Heavenly', 'Heavenly'), ('Enchanting', 'Enchanting'), ('Happy', 'Happy'), ('Sincere', 'Sincere'), ('Elegant', 'Elegant'), ('Greedy', 'Greedy'), ('Savage', 'Savage'), ('Uninteresting', 'Uninteresting'), ('Annoying', 'Annoying'), ('Freaky', 'Freaky'), ('Jealous', 'Jealous'), ('Money hungry', 'Money hungry'), ('Deceitful', 'Deceitful'), ('Impulsive', 'Impulsive'), ('Moody', 'Moody'), ('Narrow-minded', 'Narrow-minded'), ('Rude', 'Rude'), ('Unhappy', 'Unhappy'), ('Untrustworthy', 'Untrustworthy'), ('Coward', 'Coward'), ('Careless', 'Careless'), ('Bossy', 'Bossy'), ('Arrogant', 'Arrogant'), ('Boastful', 'Boastful'), ('Detached', 'Detached'), ('Egocentric', 'Egocentric'), ('Envious', 'Envious'), ('Narcissistic', 'Narcissistic'), ('Petulant', 'Petulant'), ('Vain', 'Vain'), ('Vindictive', 'Vindictive'), ('Bad-tempered', 'Bad-tempered'), ('Cynical', 'Cynical'), ('Judgmental', 'Judgmental'), ('Intolerant', 'Intolerant'), ('Resentful', 'Resentful'), ('Petty', 'Petty'), ('Unforgiving', 'Unforgiving'), ('Unreachable', 'Unreachable'), ('Vulgar', 'Vulgar'), ('Not defined', 'Not defined')], default=('Not defined', 'Not defined'), max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scores.face')),
            ],
        ),
    ]
