# Generated by Django 4.0.1 on 2022-04-25 07:58

from django.db import migrations, models
import django.db.models.deletion
import scores.validators


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(validators=[scores.validators.date_of_birth_validator])),
                ('gender', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='face',
            name='skin_color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White')], default='Black', max_length=100),
        ),
        migrations.AddField(
            model_name='score',
            name='user_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scores.userdetail'),
        ),
    ]
