# Generated by Django 4.1.3 on 2024-02-12 19:33

from django.db import migrations, models
import scores.validators


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_userdetail_ethnicity_alter_face_skin_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='face',
            name='skin_color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White')], default='Black', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(choices=[('Woman', 'Woman'), ('Man', 'Man'), ('Other', 'Other')], default='Other', max_length=100, validators=[scores.validators.gender_validator]),
        ),
    ]
