# Generated by Django 5.0.6 on 2024-08-30 09:00

import scores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_alter_face_skin_color_alter_userdetail_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='zodiac_sign',
            field=models.CharField(choices=[('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces')], default='Libra', max_length=150),
        ),
        migrations.AlterField(
            model_name='face',
            name='skin_color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White')], default='Black', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='ethnicity',
            field=models.CharField(max_length=100, validators=[scores.validators.ethnicity_validator]),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(choices=[('Woman', 'Woman'), ('Man', 'Man'), ('Other', 'Other')], default='Other', max_length=100, validators=[scores.validators.gender_validator]),
        ),
    ]
